### ISSUE TITLE
Issue dedupe refinement

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/generate-vector-embeddings#14]
Look at this [issue](https://github.com/ubq-testing/generate-vector-embeddings/issues/4)

I have used titles and bodies of three letters `asd` and variations of which is producing similarity results less than 95% which you'd expect to be 95+.

So either we must lower our threshold and/or review the logic for similarity comparisons.

**Comment by 0x4007** [comment]
Those aren't real specifications. Let's test with real specifications and refine as needed.
